# Site settings
title: Logs
description: A Blog for logging
keywords: blog
author: Shayne base on @Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "yytwz96.github.io" # the base hostname & protocol for your site
